package org.acme.insurance;



import java.lang.Number;

rule "NewTweetCEPRule"
	dialect "mvel"
	when
		tweetevent : TweetEvent( tweet matches "^(.*?(\bbad\b)[^$]*)$" ) from entry-point "TweetStream2"
		not (complaintevent : ComplaintEvent( this after tweetevent )) 
	then
		Notification fact0 = new Notification();
		fact0.setEmailid( "kasriniv@gmail.com" );
		insert( fact0 );
		System.out.println("New Tweet CEP Rule fired");
end
