package org.acme.insurance;


import org.acme.insurance.policyquote.Driver
import org.acme.insurance.policyquote.Policy

rule "PriceMultipleVehicles"
    
    ruleflow-group "total"
    salience -10

    when
        adriver: Driver()
        pMaster: Policy(driver==adriver,policyType=="MASTER",price==null)
        totalPrice: Number( intValue > 0 )
        	from accumulate( Policy(driver==adriver,policyType=="AUTO", priceVal:price),
        	sum(priceVal))
    then
        modify(pMaster) {setPrice(totalPrice.intValue())}
end
