package org.acme.insurance;



import org.acme.insurance.policyquote.Driver
import org.acme.insurance.policyquote.Policy

rule "RiskyYouth"
no-loop true
lock-on-active true
ruleflow-group "calculation"
    when
        driver : Driver(age >= 18 && < 25, numOfAccidents >= 1 || numberOfTickets >=2)
        policy : Policy(price == null, policyType == "AUTO")
    then
        modify(policy) {setPrice(700)};
        System.out.println("fired rule " + kcontext.getRule().getName());

end
