package org.acme.insurance;


import org.acme.insurance.policyquote.Driver
import org.acme.insurance.policyquote.Policy

rule "RiskyAdults"
no-loop true
lock-on-active true
ruleflow-group "calculation"
    when
        driver : Driver(age > 24, numOfAccidents >= 1 || numberOfTickets >=2)
        policy : Policy(price == null, policyType == "AUTO")
    then
        modify(policy) {setPrice(300)};
        System.out.println("fired rule " + kcontext.getRule().getName());

end
