package org.acme.insurance;



import org.acme.insurance.policyquote.Driver
import org.acme.insurance.policyquote.Policy

rule "SafeAdults"
no-loop true
lock-on-active true
ruleflow-group "calculation"
    when
        driver : Driver(age > 24, numOfAccidents < 1, numberOfTickets <= 1)
        policy : Policy(price == null, policyType == "AUTO")
    then
        modify(policy) {setPrice(120)};
        System.out.println("fired rule " + kcontext.getRule().getName());

end
