package org.acme.insurance.policyquote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "Credit Score")
   private java.lang.Integer creditscore;
   @org.kie.api.definition.type.Label(value = "DL Number")
   private java.lang.String dlNumber;
   @org.kie.api.definition.type.Label(value = "Driver Name")
   private java.lang.String driverName;
   @org.kie.api.definition.type.Label(value = "Number of Accidents")
   private java.lang.Integer numOfAccidents;
   @org.kie.api.definition.type.Label(value = "Number Of Tickets")
   private java.lang.Integer numberOfTickets;
   @org.kie.api.definition.type.Label(value = "SSN")
   private java.lang.String ssn;

   public Driver()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Integer getCreditscore()
   {
      return this.creditscore;
   }

   public void setCreditscore(java.lang.Integer creditscore)
   {
      this.creditscore = creditscore;
   }

   public java.lang.String getDlNumber()
   {
      return this.dlNumber;
   }

   public void setDlNumber(java.lang.String dlNumber)
   {
      this.dlNumber = dlNumber;
   }

   public java.lang.String getDriverName()
   {
      return this.driverName;
   }

   public void setDriverName(java.lang.String driverName)
   {
      this.driverName = driverName;
   }

   public java.lang.Integer getNumOfAccidents()
   {
      return this.numOfAccidents;
   }

   public void setNumOfAccidents(java.lang.Integer numOfAccidents)
   {
      this.numOfAccidents = numOfAccidents;
   }

   public java.lang.Integer getNumberOfTickets()
   {
      return this.numberOfTickets;
   }

   public void setNumberOfTickets(java.lang.Integer numberOfTickets)
   {
      this.numberOfTickets = numberOfTickets;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public Driver(java.lang.Integer age, java.lang.Integer creditscore,
         java.lang.String dlNumber, java.lang.String driverName,
         java.lang.Integer numOfAccidents,
         java.lang.Integer numberOfTickets, java.lang.String ssn)
   {
      this.age = age;
      this.creditscore = creditscore;
      this.dlNumber = dlNumber;
      this.driverName = driverName;
      this.numOfAccidents = numOfAccidents;
      this.numberOfTickets = numberOfTickets;
      this.ssn = ssn;
   }

}