package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class ApplicationEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Application ID")
   private java.lang.Integer applicationid;
   @org.kie.api.definition.type.Label("Application Date")
   private java.util.Date applicationdate;
   @org.kie.api.definition.type.Label("Premium")
   private java.math.BigDecimal premium;
   @org.kie.api.definition.type.Label("Insured Name")
   private java.lang.String insuredname;

   public ApplicationEvent()
   {
   }

   public java.lang.Integer getApplicationid()
   {
      return this.applicationid;
   }

   public void setApplicationid(java.lang.Integer applicationid)
   {
      this.applicationid = applicationid;
   }

   public java.util.Date getApplicationdate()
   {
      return this.applicationdate;
   }

   public void setApplicationdate(java.util.Date applicationdate)
   {
      this.applicationdate = applicationdate;
   }

   public java.math.BigDecimal getPremium()
   {
      return this.premium;
   }

   public void setPremium(java.math.BigDecimal premium)
   {
      this.premium = premium;
   }

   public java.lang.String getInsuredname()
   {
      return this.insuredname;
   }

   public void setInsuredname(java.lang.String insuredname)
   {
      this.insuredname = insuredname;
   }

   public ApplicationEvent(java.lang.Integer applicationid,
         java.util.Date applicationdate, java.math.BigDecimal premium,
         java.lang.String insuredname)
   {
      this.applicationid = applicationid;
      this.applicationdate = applicationdate;
      this.premium = premium;
      this.insuredname = insuredname;
   }

}