package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class ComplaintEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Complaint From User")
   private java.lang.String fromuser;
   @org.kie.api.definition.type.Label("Complaint category")
   private java.lang.String about;
   @org.kie.api.definition.type.Label("Complaint Text ")
   private java.lang.String complainttext;

   public ComplaintEvent()
   {
   }

   public java.lang.String getFromuser()
   {
      return this.fromuser;
   }

   public void setFromuser(java.lang.String fromuser)
   {
      this.fromuser = fromuser;
   }

   public java.lang.String getAbout()
   {
      return this.about;
   }

   public void setAbout(java.lang.String about)
   {
      this.about = about;
   }

   public java.lang.String getComplainttext()
   {
      return this.complainttext;
   }

   public void setComplainttext(java.lang.String complainttext)
   {
      this.complainttext = complainttext;
   }

   public ComplaintEvent(java.lang.String fromuser, java.lang.String about,
         java.lang.String complainttext)
   {
      this.fromuser = fromuser;
      this.about = about;
      this.complainttext = complainttext;
   }

}