package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Notification implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Agent Name")
   private java.lang.String agentname;
   @org.kie.api.definition.type.Label(value = "Email ID")
   private java.lang.String emailid;
   @org.kie.api.definition.type.Label(value = "Insured Name")
   private java.lang.String insuredname;
   @org.kie.api.definition.type.Label(value = "Quote ID")
   private java.lang.Integer quoteid;

   public Notification()
   {
   }

   public java.lang.String getAgentname()
   {
      return this.agentname;
   }

   public void setAgentname(java.lang.String agentname)
   {
      this.agentname = agentname;
   }

   public java.lang.String getEmailid()
   {
      return this.emailid;
   }

   public void setEmailid(java.lang.String emailid)
   {
      this.emailid = emailid;
   }

   public java.lang.String getInsuredname()
   {
      return this.insuredname;
   }

   public void setInsuredname(java.lang.String insuredname)
   {
      this.insuredname = insuredname;
   }

   public java.lang.Integer getQuoteid()
   {
      return this.quoteid;
   }

   public void setQuoteid(java.lang.Integer quoteid)
   {
      this.quoteid = quoteid;
   }

   public Notification(java.lang.String agentname, java.lang.String emailid,
         java.lang.String insuredname, java.lang.Integer quoteid)
   {
      this.agentname = agentname;
      this.emailid = emailid;
      this.insuredname = insuredname;
      this.quoteid = quoteid;
   }

}