package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
public class QuoteEvent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public QuoteEvent()
   {
   }

}